### ISSUE TITLE
Enforce max player count

### ISSUE THREAD

**Issue by TomAFrench** [Good-Ghosting/goodghosting-smart-contracts#48]
As `allocateWithdrawAmounts` iterates through the array of all players, it's susceptible to out of gas errors (whether malicious or accidental).

Two possible solutions to this are to add a `require(players.length <= maxPlayerCount, "Too many players")` statement to `joinGame` or refactor `allocateWithdrawAmounts` so that it can resolve a smaller number of players at a time. The second solution may be overkill for the time being.

**Comment by TomAFrench** [comment]
`allocateWithdrawAmounts` is gone in #50 which tackles the possibility for out of gas errors

**Comment by fodisi** [comment]
PR #50 is now merged. Closing this issue.
@TomAFrench Thanks again for addressing it!
