### ISSUE TITLE
Add whitelist

### ISSUE THREAD

**Issue by Deepcryptodive** [Good-Ghosting/goodghosting-smart-contracts#84]
e.g. only allow ETH addresses that are on a list (published on-chain beforehand), to call `joinGame`.

Why?
- To avoid people gaming the additional rewards in 'sponsored pools'
- To enable access to 'exclusive pools'  (e.g. members of a specific DAO or people that interacted with protocol X).

**Comment by Deepcryptodive** [comment]
_cf. @viraj124 :
"We can use **Uniswap's Merkel Distributor contracts** which they used for UNI Claim  so basically we get user responses on a sheet with their addresses create a json with the structure => address: true (where true signifies the address is a valid address) then create a merkel root and set it on chain while our contract deployment and while joining game we pass in a proof param and  check whether the address can join or not"_

**Comment by fodisi** [comment]
Merged in PR #87
